name: 'PNPM + Bun setup'
description: 'Shared action to install PNPM and Bun'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v1.0.22

    - uses: pnpm/action-setup@v2.4.0
      name: Install pnpm
      with:
        version: 8.12.1
        run_install: true

    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'
