version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - raulfdm
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 15.a, < 16"
  - dependency-name: algoliasearch
    versions:
    - 4.9.0
    - 4.9.1
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.13
  - dependency-name: react-intl
    versions:
    - 5.15.4
    - 5.16.0
    - 5.17.0
    - 5.17.1
    - 5.17.2
  - dependency-name: framer-motion
    versions:
    - 4.1.10
    - 4.1.11
    - 4.1.8
    - 4.1.9
  - dependency-name: "@headlessui/react"
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: netlify-lambda
    versions:
    - 2.0.4
    - 2.0.5
  - dependency-name: "@raulfdm/blog-tailwind-preset"
    versions:
    - 2.3.0
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.76
  - dependency-name: eslint-config-prettier
    versions:
    - 8.3.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.6
  - dependency-name: next
    versions:
    - 10.1.0
    - 10.1.4-canary.15
    - 10.1.4-canary.16
  - dependency-name: semantic-release-monorepo
    versions:
    - 7.0.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
    - 2.1.2
  - dependency-name: react-use
    versions:
    - 17.2.3
    - 17.2.4
  - dependency-name: unist-util-visit
    versions:
    - 3.0.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name: unist-util-filter
    versions:
    - 3.0.0
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.2.0
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/addons"
    versions:
    - 6.2.0
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.0
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.8
    - 6.2.9
  - dependency-name: unist-util-visit-parents
    versions:
    - 4.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.16
  - dependency-name: "@types/classnames"
    versions:
    - 2.3.1
  - dependency-name: strapi-plugin-content-type-builder
    versions:
    - 3.5.3
    - 3.6.0
  - dependency-name: strapi-utils
    versions:
    - 3.5.3
    - 3.6.0
  - dependency-name: strapi-plugin-documentation
    versions:
    - 3.6.0
  - dependency-name: strapi-connector-mongoose
    versions:
    - 3.6.0
  - dependency-name: strapi-plugin-upload
    versions:
    - 3.5.3
    - 3.6.0
  - dependency-name: strapi-plugin-email
    versions:
    - 3.6.0
  - dependency-name: strapi-plugin-users-permissions
    versions:
    - 3.6.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: next-mdx-remote
    versions:
    - 2.1.4
  - dependency-name: "@emotion/jest"
    versions:
    - 11.3.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
    - 4.22.0
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: next-sitemap
    versions:
    - 1.6.13
    - 1.6.16
    - 1.6.20
    - 1.6.25
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.3
  - dependency-name: autoprefixer
    versions:
    - 10.2.5
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.1.0
  - dependency-name: yargs-parser
    versions:
    - 20.2.4
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: kind-of
    versions:
    - 6.0.3
  - dependency-name: dot-prop
    versions:
    - 5.3.0
