# fly.toml app configuration file generated for raulmelo-studio-fragrant-dust-2943 on 2023-12-03T14:55:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "raulmelo-studio-fragrant-dust-2943"
primary_region = "gig"

# [deploy]
# strategy = "bluegreen"

[build]
dockerfile = "./apps/website/Dockerfile"
build-target = "runner"

[http_service]
internal_port = 8080
force_https = false
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
