packages:
  - website
  - website-new
  - packages/*
  - cms

catalog:
  '@types/bun': 1.3.2
  eslint: 10.0.3
  prettier: 3.6.2
  tsdown: 0.18.2
  typescript: 5.9.3
  vitest: 4.0.18
  zod: 3.25.76

inject-workspace-packages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
