packages:
  - website
  - website-new
  - packages/*
  - cms

catalog:
  '@types/bun': 1.3.2
  eslint: 9.34.0
  prettier: 3.6.2
  typescript: 5.9.2
  vitest: 3.2.4
  zod: 3.25.76

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
