import {
  IconAlertOctagon,
  IconBrandCodepen,
  IconBrandTwitter,
  IconCode,
  IconDots,
  IconExternalLink,
  IconHash,
  IconHighlight,
  IconInfoHexagon,
  IconLink,
  IconNotes,
  IconPhoto,
  IconSlideshow,
  IconSpeakerphone,
  IconStrikethrough,
} from '@tabler/icons-react';

export {
  IconAlertOctagon,
  IconBrandCodepen,
  IconBrandTwitter,
  IconCode,
  IconDots,
  IconExternalLink,
  IconHash,
  IconHighlight,
  IconInfoHexagon,
  IconLink,
  IconNotes,
  IconPhoto,
  IconSlideshow,
  IconSpeakerphone,
  IconStrikethrough,
};
