name: 'Bun setup'
description: 'Shared action to install PNPM and Bun'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Install dependencies
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'pnpm'

    - name: Install dependencies
      shell: 'bash'
      run: pnpm install
