export {
  IconAlertOctagon,
  IconBrandCodepen,
  IconBrandX,
  IconCode,
  IconDots,
  IconExternalLink,
  IconHash,
  IconHighlight,
  IconInfoHexagon,
  IconLink,
  IconNotes,
  IconPhoto,
  IconSlideshow,
  IconSpeakerphone,
  IconStrikethrough,
} from '@tabler/icons-react';
