version: '3.9'
services:
  server:
    image: 'raulfdm/raulmelo.dev-cms'
    ports:
      - '1337:1337'
    env_file:
      - .env

  web:
    depends_on:
      - server
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/app
