name: TESSST

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install lerna and netlify
        run: yarn global add nx

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Test, build and lint
        run: yarn nx run-many --target=build, --all --parallel

      - name: Test
        run: yarn nx run-many --target=test --all --parallel

      - name: lint
        run: yarn nx run-many --target=lint --all --parallel
