name: TESSST

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build,deploy,test
          affected: 'true'
          projects: all
