name: CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/bun

      - name: CI checks
        run: bun turbo lint test build
        env:
          APP_ENV: local
