name: CMS Deploy

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/bun

      - name: CI checks
        run: bun turbo deploy --filter=cms
        env:
          SANITY_AUTH_TOKEN: ${{ env.SANITY_AUTH_TOKEN }}
