name: Playwright Tests

on:
  push:
    branches: [main]
    paths:
      - 'website-new/**'
  pull_request:
    paths:
      - 'website-new/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/bun

      - name: Install Playwright Browsers
        run: bun playwright install --with-deps

      - name: Run Playwright tests
        run: bun turbo test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./website-new/playwright-report/
          retention-days: 30
