name: Fitness Buddy

on:
  push:
    paths:
      - '.github/workflows/fitness-buddy.yml'
      - 'apps/fitness-buddy/**'
      - 'packages/core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/pnpm-bun-setup

      - name: Lint Projects
        run: pnpm run lint --filter=fitness-buddy
