name: Fitness Buddy

on:
  push:
    paths:
      - 'apps/fitness-buddy/**'
      - 'packages/core/**'
      - '.github/workflows/fitness-buddy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Test Projects
        run: bun --bun run test --filter fitness-buddy

      - name: Lint Projects
        run: bun --bun run lint --filter fitness-buddy
