name: Fitness Buddy

on:
  push:
    paths:
      - '.github/workflows/fitness-buddy.yml'
      - 'apps/fitness-buddy/**'
      - 'packages/core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8.9.2
          run_install: true

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Lint Projects
        run: bun run lint --filter=fitness-buddy
