name: Fitness Buddy

on:
  push:
    paths:
      - 'apps/fitness-buddy/**'
      - 'packages/core/**'
      - 'packages/vercel-utils/**'
      - '.github/workflows/fitness-buddy.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: |
          pnpm install --global vercel
          pnpm install --frozen-lockfile --shamefully-hoist

      - name: Test Projects
        run: pnpm --filter fitness-buddy run check

      - name: Lint Projects
        run: pnpm --filter fitness-buddy run lint

      - name: Build application for Preview
        run: |
          pnpm --filter fitness-buddy run generate-vercel
          vercel build
        working-directory: apps/fitness-buddy
        if: contains('refs/heads/main', github.ref) == false
        env:
          VERCEL: true # This enables build for vercel using @sveltekit/adapter-auto
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FITNESS }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_MAIN }}
          ENVIRONMENT: preview

      - name: Vercel Deploy - Preview
        uses: amondnet/vercel-action@v20
        if: contains('refs/heads/main', github.ref) == false
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }} # Required
          github-token: ${{ github.token }} #Optional
          vercel-args: --prebuilt
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_MAIN}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FITNESS}} #Required
          working-directory: apps/fitness-buddy

      - name: Build application for Production
        run: |
          pnpm --filter fitness-buddy run generate-vercel
          vercel build --prod
        working-directory: apps/fitness-buddy
        if: contains('refs/heads/main', github.ref) == true
        env:
          VERCEL: true # This enables build for vercel using @sveltekit/adapter-auto
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FITNESS }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_MAIN }}
          ENVIRONMENT: production

      - name: Vercel Deploy - Production
        uses: amondnet/vercel-action@v20
        if: contains('refs/heads/main', github.ref) == true
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }} # Required
          github-token: ${{ github.token }} #Optional
          vercel-args: '--prebuilt --prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_MAIN}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FITNESS}} #Required
          working-directory: apps/fitness-buddy
