name: Fitness Buddy

on:
  push:
    paths:
      - 'apps/fitness-buddy/**'
      - 'packages/core/**'
      - '.github/workflows/fitness-buddy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build dependants
        # BUG: https://github.com/oven-sh/bun/issues/4447#issuecomment-1712927579
        run: bun run build --filter=fitness-buddy^...

      - name: Lint Projects
        working-directory: apps/fitness-buddy
        run: bun run lint
