name: Renovate
on:
  workflow_dispatch:
    secrets:
      RENOVATE_TOKEN:
        required: true
    inputs:
      logLevel:
        description: 'Reason'
        required: false
        default: 'Checking for updates'
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 * * *' # At 00:00 /> https://crontab.guru/#0_0_*_*_*

jobs:
  renovate:
    environment: Raul Melo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.127.2
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
