name: Website - Deploy

on:
  push:
    branches:
      - main
      - test-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.131

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
