name: Website - CI

on:
  push:
    paths:
      - .github/workflows/website.yml
      - .github/actions/pnpm-bun-setup/action.yml
      - apps/website/**
      - packages/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/pnpm-bun-setup

      - name: Build
        run: |
          pnpm run build --filter=website

      - name: Lint Projects
        run: pnpm run lint --filter website

      - name: Test Projects
        run: pnpm run test --filter website
